export type Languages = 'RU' | 'EN';

export type Vocabulary = {
    login_button: string,
    header_text_1: string,
    header_text_2: string,
    header_text_3: string,
    header_text_4: string,
    header_text_more: string,
    header_top_up: string,
    header_pixels_1: string,
    header_pixels_2: string,
    menu_about: string,
    menu_stats: string,
    menu_faq: string,
    menu_contact: string,
    login_desktop_title: string,
    login_desktop_caption: string,
    login_mobile_title: string,
    login_mobile_caption: string,
    profile_auth_required: string,
    profile_empty_items: string,
    profile_items_title: string,
    profile_logged_title: string,
    profile_wallet_withdraw: string,
    profile_wallet_recover: string,
    profile_wallet_export: string,
};

export const vocabulary = {

    RU : {
        login_button: 'Войти через Telegram',
        header_text_1 : 'Это холст 1000х1000 пикселей.',
        header_text_2 : 'Авторизуйся, пополни баланс TON',
        header_text_3 : 'и нарисуй всё, что захочешь!',
        header_text_4 : 'Один пиксель стоит 0.001 TON.',
        header_text_more : 'Узнать больше',
        header_top_up : 'Пополнить',
        header_pixels_1 : 'пиксел|ь|я|ей',
        header_pixels_2 : 'остал|ся|ось|ось',
        menu_about : 'О проекте',
        menu_stats : 'Статистика',
        menu_faq : 'FAQ',
        menu_contact : 'Контакты',
        login_desktop_title : 'Отсканируйте QR-код камерой вашего смартфона',
        login_desktop_caption : 'Мы не получаем и не храним ваши авторизационные данные. Ваш кошелёк в безопасности.',
        login_mobile_title : 'Используйте кнопку для авторизации через Tonkeeper.',
        login_mobile_caption : 'Мы не получаем и не храним ваши авторизационные данные. Ваш кошелёк в безопасности.',
        profile_auth_required : 'Для просмотра профиля необходимо авторизоваться.',
        profile_empty_items : 'Вы еще не купили ни одного места на холсте. Возможно, сейчас самое время?',
        profile_items_title : 'Ваши места на холсте',
        profile_logged_title : 'Вы вошли через Telegram',
        profile_wallet_withdraw : 'Вывести средства',
        profile_wallet_recover: 'Восстановить кошелек',
        profile_wallet_export: 'Экспортировать пароль',
    },

    EN : {
        login_button: 'Login via Telegram',
        header_text_1 : 'There is a 1000x1000px canvas.',
        header_text_2 : 'Login, top-up TON balance',
        header_text_3 : 'and draw anything you want!',
        header_text_4 : 'One pixel is 0.001 TON.',
        header_text_more : 'Learn more',
        header_top_up : 'Top up',
        header_pixels_1 : 'pixel||s|s',
        header_pixels_2 : 'remaining|||',
        menu_about : 'About',
        menu_stats : 'Stats',
        menu_faq : 'FAQ',
        menu_contact : 'Contact us',
        login_desktop_title: 'Scan the QR code with your phone’s camera',
        login_desktop_caption: 'We neither receive nor store your wallet log-in details; therefore, your TON is safe.',
        login_mobile_title : 'Use this button to login via Tonkeeper',
        login_mobile_caption : 'We neither receive nor store your wallet log-in details; therefore, your TON is safe.',
        profile_auth_required: 'Authorization is required to view your profile.',
        profile_empty_items : 'You haven\'t bought any of our canvas places yet. Maybe it\'s time?',
        profile_items_title : 'Your places on canvas',
        profile_logged_title : 'Logged in via Telegram',
        profile_wallet_withdraw : 'Withdraw funds',
        profile_wallet_recover: 'Recover wallet',
        profile_wallet_export: 'Export passphrase',
    },

};